[package]
name = "mini_server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]   # build a shared library for Python

[dependencies]
pyo3 = { version = "0.26.0", features = ["extension-module"] }
